# Generated by Django 2.1.1 on 2019-04-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
        ('users', '0002_auto_20190408_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=models.ManyToManyField(to='maker.CryptoCurrency'),
        ),
    ]
