# Generated by Django 2.1.1 on 2019-03-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='privacy',
            field=models.FloatField(verbose_name='privacy'),
        ),
    ]
