# Generated by Django 2.1.1 on 2019-03-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0002_auto_20190327_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='time',
        ),
    ]
