# Generated by Django 2.1.1 on 2019-04-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0002_cryptocurrency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='description',
            field=models.TextField(null=True, verbose_name='About'),
        ),
    ]
