# Generated by Django 2.1.1 on 2019-03-28 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0005_auto_20190327_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maker.Timeslot'),
        ),
    ]
