# Generated by Django 2.1.1 on 2019-04-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0006_auto_20190327_2231'),
        ('maker', '0003_cryptocurrency_description'),
    ]

    operations = [
    ]
